=== gdmatrix/gdmatrix4/modules/module.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           targetNamespace="http://schema.gdmatrix.org"
           xmlns="http://schema.gdmatrix.org"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="Component">
  </xs:complexType>

  <xs:complexType name="Import">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:attribute name="prefix" type="xs:string" use="optional" />
        <xs:attribute name="module" type="xs:string" use="optional" />
        <xs:attribute name="namespace" type="xs:string" use="optional" />
        <xs:attribute name="location" type="xs:string" use="optional" />
        <xs:attribute name="virtual" type="xs:boolean" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Attribute">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:attribute name="name" type="xs:string"  />
        <xs:attribute name="value" type="xs:string"  />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Documentation" mixed="true">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:sequence>
          <xs:any minOccurs="0" maxOccurs="unbounded"
                  namespace="##any" processContents="skip" />
        </xs:sequence>
        <xs:attribute name="language" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="NamedComponent">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="attribute" type="Attribute" />
          <xs:element name="documentation" type="Documentation" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string"  />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TypifiedComponent">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:attribute name="type" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ComplexTypifiedComponent">
    <xs:complexContent>
      <xs:extension base="TypifiedComponent">
        <xs:attribute name="minOccurs" type="xs:int"  use="optional"/>
        <xs:attribute name="maxOccurs" type="xs:string" use="optional"/>
        <xs:attribute name="references" type="xs:string" use="optional"/>
        <xs:attribute name="readOnly" type="xs:string" use="optional"/>
        <xs:attribute name="nillable" type="xs:string" use="optional"/>
        <xs:attribute name="expectedContentTypes" type="xs:string" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Identifier">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Type">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:attribute name="extends" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ComplexType">
    <xs:complexContent>
      <xs:extension base="Type">
        <xs:sequence>
          <xs:element name="identifier" type="Identifier" minOccurs="0" />
          <xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Property">
    <xs:complexContent>
      <xs:extension base="ComplexTypifiedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Parameter">
    <xs:complexContent>
      <xs:extension base="ComplexTypifiedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Response">
    <xs:complexContent>
      <xs:extension base="ComplexTypifiedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Error">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:attribute name="message" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Entity">
    <xs:complexContent>
      <xs:extension base="ComplexType">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Struct">
    <xs:complexContent>
      <xs:extension base="ComplexType">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="EnumerationValue">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Enumeration">
    <xs:complexContent>
      <xs:extension base="Type">
        <xs:sequence>
          <xs:element name="value" type="EnumerationValue" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Operation">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:sequence>
          <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
          <xs:element name="response" type="Response" minOccurs="0" />
          <xs:element name="error" type="Error" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Module">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:sequence>
          <xs:element name="imports" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="import" type="Import" minOccurs="0" maxOccurs="unbounded" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="types" minOccurs="0">
            <xs:complexType>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="entity" type="Entity" />
                <xs:element name="struct" type="Struct" />
                <xs:element name="enumeration" type="Enumeration" />
              </xs:choice>
            </xs:complexType>
          </xs:element>
          <xs:element name="operations" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="operation" type="Operation" minOccurs="0" maxOccurs="unbounded" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="namespace" type="xs:anyURI" />
        <xs:attribute name="title" type="xs:string" />
        <xs:attribute name="manager" type="xs:string" />
        <xs:attribute name="version" type="xs:float" />
        <xs:attribute name="status" type="xs:string" />
        <xs:attribute name="authors" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="module" type="Module" />

</xs:schema>

=== gdmatrix/gdmatrix4/modules/forum.xml
<?xml version="1.0" encoding="UTF-8"?>
<module
  xmlns="http://schema.gdmatrix.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schema.gdmatrix.org module.xsd"
  name="forum"
  namespace="http://forum.matrix.org/"
  title="Forum manager"
  manager="ForumManager"
  version="1.0"
  status="REVISION"
  authors="Jordi Lopez, Abel Blanque, Ricard Real">

  <attribute name="jaxws.wsdlLocation" value="/services/forum?wsdl" />
  <attribute name="jaxrs.path" value="/forum" />

  <imports>
    <import prefix="mx"
      namespace="http://base.matrix.org/"
      location="matrix.xsd" />
  </imports>

  <types>

    <entity name="Forum">
      <identifier name="forumId">
      </identifier>
      <property name="startDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="endDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="name" type="xs:string" minOccurs="0">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="type" type="forum:ForumType" minOccurs="0">
      </property>
      <property name="emailFrom" type="xs:string" minOccurs="0">
      </property>
      <property name="emailTo" type="xs:string" minOccurs="0">
      </property>
      <property name="lastInputIndex" type="xs:int">
      </property>
      <property name="lastOutputIndex" type="xs:int">
      </property>
      <property name="group" type="xs:string" minOccurs="0">
      </property>
      <property name="adminRoleId" type="xs:string" minOccurs="0">
      </property>
      <property name="maxQuestions" type="xs:int">
      </property>
      <property name="creationUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="creationDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="changeUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="changeDateTime" type="mx:dateTime" minOccurs="0">
      </property>
    </entity>

    <entity name="Question">
      <identifier name="questionId">
      </identifier>
      <property name="forumId" type="xs:string" minOccurs="0"
        references="forum:Forum">
      </property>
      <property name="inputIndex" type="xs:int">
      </property>
      <property name="outputIndex" type="xs:int">
      </property>
      <property name="title" type="xs:string" minOccurs="0">
      </property>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="readCount" type="xs:int">
      </property>
      <property name="visible" type="xs:boolean">
      </property>
      <property name="creationUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="creationDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="changeUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="changeDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="activityDateTime" type="mx:dateTime" minOccurs="0">
      </property>
    </entity>

    <entity name="Answer">
      <identifier name="answerId">
      </identifier>
      <property name="questionId" type="xs:string" minOccurs="0"
        references="forum:Question">
      </property>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="comments" type="xs:string" minOccurs="0">
      </property>
      <property name="creationUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="creationDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="changeUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="changeDateTime" type="mx:dateTime" minOccurs="0">
      </property>
    </entity>

    <struct name="ForumView">
      <property name="forum" type="forum:Forum" minOccurs="0">
      </property>
      <property name="visibleQuestionCount" type="xs:int">
      </property>
      <property name="visibleAnswerCount" type="xs:int">
      </property>
      <property name="pendentQuestionCount" type="xs:int">
      </property>
      <property name="editable" type="xs:boolean">
      </property>
      <property name="status" type="forum:ForumStatus">
      </property>
    </struct>

    <struct name="QuestionView">
      <property name="question" type="forum:Question" minOccurs="0">
      </property>
      <property name="answer" type="forum:Answer" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </property>
    </struct>

    <struct name="ForumFilter">
      <property name="forumId" type="xs:string" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </property>
      <property name="name" type="xs:string" minOccurs="0">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="group" type="xs:string" minOccurs="0">
      </property>
      <property name="firstResult" type="xs:int">
      </property>
      <property name="maxResults" type="xs:int">
      </property>
    </struct>

    <struct name="QuestionFilter">
      <property name="questionId" type="xs:string" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </property>
      <property name="forumId" type="xs:string" minOccurs="0">
      </property>
      <property name="showAnswered" type="forum:ShowAnswered" minOccurs="0">
      </property>
      <property name="showVisible" type="forum:ShowVisible" minOccurs="0">
      </property>
      <property name="orderBy" type="forum:OrderBy" minOccurs="0">
      </property>
      <property name="creationUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="firstResult" type="xs:int">
      </property>
      <property name="maxResults" type="xs:int">
      </property>
    </struct>

    <enumeration name="ForumStatus">
      <value name="OPEN_BEFORE"/>
      <value name="CLOSED_BEFORE"/>
      <value name="OPEN"/>
      <value name="CLOSED"/>
    </enumeration>

    <enumeration name="ForumType">
      <value name="NORMAL"/>
      <value name="INTERVIEW"/>
      <value name="UNCENSORED_INTERVIEW"/>
    </enumeration>

    <enumeration name="ShowAnswered">
      <value name="YES"/>
      <value name="NO"/>
    </enumeration>

    <enumeration name="ShowVisible">
      <value name="YES"/>
      <value name="NO"/>
    </enumeration>

    <enumeration name="OrderBy">
      <value name="ACTIVITY"/>
      <value name="INPUTINDEX"/>
      <value name="OUTPUTINDEX"/>
      <value name="USER"/>
    </enumeration>

  </types>

  <operations>

    <operation name="loadForum">
      <parameter name="forumId" type="xs:string">
      </parameter>
      <response name="forum" type="forum:Forum">
      </response>
    </operation>

    <operation name="storeForum">
      <parameter name="forum" type="forum:Forum">
      </parameter>
      <response name="storedForum" type="forum:Forum">
      </response>
    </operation>

    <operation name="removeForum">
      <parameter name="forumId" type="xs:string">
      </parameter>
      <response name="removed" type="xs:boolean">
      </response>
    </operation>

    <operation name="loadQuestion">
      <parameter name="questionId" type="xs:string">
      </parameter>
      <response name="question" type="forum:Question">
      </response>
    </operation>

    <operation name="storeQuestion">
      <parameter name="question" type="forum:Question">
      </parameter>
      <response name="storedQuestion" type="forum:Question">
      </response>
    </operation>

    <operation name="removeQuestion">
      <parameter name="questionId" type="xs:string">
      </parameter>
      <response name="removed" type="xs:boolean">
      </response>
    </operation>

    <operation name="readQuestion">
      <parameter name="questionId" type="xs:string">
      </parameter>
      <response name="question" type="forum:Question">
      </response>
    </operation>

    <operation name="loadAnswer">
      <parameter name="answerId" type="xs:string">
      </parameter>
      <response name="answer" type="forum:Answer">
      </response>
    </operation>

    <operation name="storeAnswer">
      <parameter name="answer" type="forum:Answer">
      </parameter>
      <response name="storedAnswer" type="forum:Answer">
      </response>
    </operation>

    <operation name="removeAnswer">
      <parameter name="answerId" type="xs:string">
      </parameter>
      <response name="removed" type="xs:boolean">
      </response>
    </operation>

    <operation name="countForums">
      <parameter name="filter" type="forum:ForumFilter">
      </parameter>
      <response name="forumCount" type="xs:int">
      </response>
    </operation>

    <operation name="findForums">
      <parameter name="filter" type="forum:ForumFilter">
      </parameter>
      <response name="forum" type="forum:Forum" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="findForumViews">
      <parameter name="filter" type="forum:ForumFilter">
      </parameter>
      <response name="forumView" type="forum:ForumView" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="countQuestionViews">
      <parameter name="filter" type="forum:QuestionFilter">
      </parameter>
      <response name="questionViewCount" type="xs:int">
      </response>
    </operation>

    <operation name="findQuestionViews">
      <parameter name="filter" type="forum:QuestionFilter">
      </parameter>
      <response name="questionView" type="forum:QuestionView" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

  </operations>

</module>

=== gdmatrix/gdmatrix4/modules/translation.xml
<?xml version="1.0" encoding="UTF-8"?>
<module
  xmlns="http://schema.gdmatrix.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schema.gdmatrix.org module.xsd"
  name="translation"
  namespace="http://translation.matrix.org/"
  title="Translation manager"
  manager="TranslationManager"
  version="1.0"
  status="FINAL"
  authors="Ricard Real, Jordi LÃ³pez">

  <attribute name="jaxws.wsdlLocation" value="/services/translation?wsdl" />
  <attribute name="jaxrs.path" value="/translation" />

  <imports>
    <import prefix="mx"
      namespace="http://base.matrix.org/"
     location="matrix.xsd" />
  </imports>

  <types>
    <entity name="Translation">
      <identifier name="transId">
      </identifier>
      <property name="language" type="xs:string" minOccurs="0">
      </property>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="translation" type="xs:string" minOccurs="0">
      </property>
      <property name="state" type="translation:TranslationState" minOccurs="0">
      </property>
      <property name="group" type="xs:string" minOccurs="0">
      </property>
      <property name="creationDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="modifyDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="readDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="modifyUserId" type="xs:string" minOccurs="0">
      </property>
    </entity>

    <struct name="TranslationMetaData">
      <property name="translationMaxSize" type="xs:int">
      </property>
    </struct>

    <struct name="TranslationFilter">
      <property name="language" type="xs:string" minOccurs="0">
      </property>
      <property name="state" type="translation:TranslationState" minOccurs="0">
      </property>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="translation" type="xs:string" minOccurs="0">
      </property>
      <property name="group" type="xs:string" minOccurs="0">
      </property>
      <property name="firstResult" type="xs:int">
      </property>
      <property name="maxResults" type="xs:int">
      </property>
    </struct>

    <enumeration name="TranslationState">
      <value name="DRAFT"/>
      <value name="COMPLETED"/>
    </enumeration>
  </types>

  <operations>

    <operation name="getTranslationMetaData">
      <response name="translationMetaData" type="translation:TranslationMetaData">
      </response>
    </operation>

    <operation name="translateGroup">
      <parameter name="language" type="xs:string">
      </parameter>
      <parameter name="text" type="xs:string">
      </parameter>
      <parameter name="group" type="xs:string">
      </parameter>
      <response name="translation" type="translation:Translation" minOccurs="0" maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="loadTranslation">
      <parameter name="transId" type="xs:string">
      </parameter>
      <response name="translation" type="translation:Translation">
      </response>
    </operation>

    <operation name="storeTranslation">
      <parameter name="translation" type="translation:Translation">
      </parameter>
      <response name="storedTranslation" type="translation:Translation">
      </response>
    </operation>

    <operation name="removeTranslation">
      <parameter name="transId" type="xs:string">
      </parameter>
      <response name="removed" type="xs:boolean">
      </response>
    </operation>

    <operation name="findTranslations">
      <parameter name="filter" type="translation:TranslationFilter">
      </parameter>
      <response name="translation" type="translation:Translation" minOccurs="0" maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="countTranslations">
      <parameter name="filter" type="translation:TranslationFilter">
      </parameter>
      <response name="translationCount" type="xs:int">
      </response>
    </operation>

    <operation name="listModifiedTranslations">
      <parameter name="language" type="xs:string">
      </parameter>
      <parameter name="dateTime1" type="xs:string">
      </parameter>
      <parameter name="dateTime2" type="xs:string">
      </parameter>
      <response name="translation" type="xs:string" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="setActiveTranslations">
      <parameter name="translation" type="translation:Translation"
        minOccurs="0" maxOccurs="unbounded" nillable="true">
      </parameter>
      <response name="numUpdated" type="xs:int">
      </response>
    </operation>

    <operation name="translate">
      <parameter name="language" type="xs:string">
      </parameter>
      <parameter name="text" type="xs:string">
      </parameter>
      <parameter name="group" type="xs:string">
      </parameter>
      <response name="translation" type="translation:Translation">
      </response>
    </operation>
  </operations>
</module>

=== gdmatrix/gdmatrix4/modules/survey.xml
<?xml version="1.0" encoding="UTF-8"?>
<module
  xmlns="http://schema.gdmatrix.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schema.gdmatrix.org module.xsd"
  name="survey"
  namespace="http://survey.matrix.org/"
  title="Survey manager"
  manager="SurveyManager"
  version="1.0"
  status="REVISION"
  authors="Jordi LÃ³pez">

  <attribute name="jaxws.wsdlLocation" value="/services/survey?wsdl" />
  <attribute name="jaxrs.path" value="/survey" />

  <imports>
    <import prefix="mx"
      namespace="http://base.matrix.org/"
     location="matrix.xsd" />
  </imports>

  <types>

    <entity name="Survey">
      <identifier name="surveyId">
      </identifier>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="open" type="xs:boolean">
      </property>
      <property name="answerList" type="survey:AnswerList" minOccurs="0">
      </property>
      <property name="voteCount" type="xs:int">
      </property>
    </entity>

    <entity name="Answer">
      <identifier name="answerId">
      </identifier>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="voteCount" type="xs:int">
      </property>
    </entity>

    <struct name="SurveyMetaData">
      <property name="surveyTextMaxSize" type="xs:int">
      </property>
      <property name="answerTextMaxSize" type="xs:int">
      </property>
    </struct>

    <struct name="AnswerList">
      <property name="answerList" type="survey:Answer" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </property>
    </struct>

    <struct name="SurveyTable">
      <property name="surveyViewList" type="survey:SurveyView"
        minOccurs="0" maxOccurs="unbounded" nillable="true">
      </property>
    </struct>

    <struct name="SurveyView">
      <property name="surveyId" type="xs:string" minOccurs="0">
      </property>
      <property name="text" type="xs:string" minOccurs="0">
      </property>
      <property name="open" type="xs:boolean">
      </property>
      <property name="startDay" type="xs:string" minOccurs="0">
      </property>
      <property name="voteCount" type="xs:int">
      </property>
    </struct>
  </types>

  <operations>

    <operation name="getSurveyMetaData">
      <response name="surveyMetaData" type="survey:SurveyMetaData">
      </response>
    </operation>

    <operation name="storeSurvey">
      <parameter name="text" type="xs:string">
      </parameter>
      <parameter name="answers" type="xs:string" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </parameter>
      <response name="return" type="xs:string">
      </response>
    </operation>

    <operation name="openSurvey">
      <parameter name="surveyId" type="xs:string">
      </parameter>
    </operation>

    <operation name="closeSurvey">
      <parameter name="surveyId" type="xs:string">
      </parameter>
    </operation>

    <operation name="voteSurvey">
      <parameter name="surveyId" type="xs:string">
      </parameter>
      <parameter name="answerId" type="xs:string">
      </parameter>
    </operation>

    <operation name="loadSurvey">
      <parameter name="document" type="xs:string">
      </parameter>
      <response name="survey" type="survey:Survey">
      </response>
    </operation>

    <operation name="findSurveys">
      <response name="surveyTable" type="survey:SurveyTable">
      </response>
    </operation>
  </operations>
</module>
