=== gdmatrix/gdmatrix4/modules/module.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           targetNamespace="http://schema.gdmatrix.org"
           xmlns="http://schema.gdmatrix.org"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="Component">
  </xs:complexType>

  <xs:complexType name="Import">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:attribute name="prefix" type="xs:string" use="optional" />
        <xs:attribute name="module" type="xs:string" use="optional" />
        <xs:attribute name="namespace" type="xs:string" use="optional" />
        <xs:attribute name="location" type="xs:string" use="optional" />
        <xs:attribute name="virtual" type="xs:boolean" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Attribute">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:attribute name="name" type="xs:string"  />
        <xs:attribute name="value" type="xs:string"  />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Documentation" mixed="true">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:sequence>
          <xs:any minOccurs="0" maxOccurs="unbounded"
                  namespace="##any" processContents="skip" />
        </xs:sequence>
        <xs:attribute name="language" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="NamedComponent">
    <xs:complexContent>
      <xs:extension base="Component">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="attribute" type="Attribute" />
          <xs:element name="documentation" type="Documentation" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string"  />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TypifiedComponent">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:attribute name="type" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ComplexTypifiedComponent">
    <xs:complexContent>
      <xs:extension base="TypifiedComponent">
        <xs:attribute name="minOccurs" type="xs:int"  use="optional"/>
        <xs:attribute name="maxOccurs" type="xs:string" use="optional"/>
        <xs:attribute name="references" type="xs:string" use="optional"/>
        <xs:attribute name="readOnly" type="xs:string" use="optional"/>
        <xs:attribute name="nillable" type="xs:string" use="optional"/>
        <xs:attribute name="expectedContentTypes" type="xs:string" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Identifier">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Type">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:attribute name="extends" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ComplexType">
    <xs:complexContent>
      <xs:extension base="Type">
        <xs:sequence>
          <xs:element name="identifier" type="Identifier" minOccurs="0" />
          <xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Property">
    <xs:complexContent>
      <xs:extension base="ComplexTypifiedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Parameter">
    <xs:complexContent>
      <xs:extension base="ComplexTypifiedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Response">
    <xs:complexContent>
      <xs:extension base="ComplexTypifiedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Error">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:attribute name="message" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Entity">
    <xs:complexContent>
      <xs:extension base="ComplexType">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Struct">
    <xs:complexContent>
      <xs:extension base="ComplexType">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="EnumerationValue">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Enumeration">
    <xs:complexContent>
      <xs:extension base="Type">
        <xs:sequence>
          <xs:element name="value" type="EnumerationValue" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Operation">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:sequence>
          <xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
          <xs:element name="response" type="Response" minOccurs="0" />
          <xs:element name="error" type="Error" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Module">
    <xs:complexContent>
      <xs:extension base="NamedComponent">
        <xs:sequence>
          <xs:element name="imports" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="import" type="Import" minOccurs="0" maxOccurs="unbounded" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="types" minOccurs="0">
            <xs:complexType>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="entity" type="Entity" />
                <xs:element name="struct" type="Struct" />
                <xs:element name="enumeration" type="Enumeration" />
              </xs:choice>
            </xs:complexType>
          </xs:element>
          <xs:element name="operations" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="operation" type="Operation" minOccurs="0" maxOccurs="unbounded" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="namespace" type="xs:anyURI" />
        <xs:attribute name="title" type="xs:string" />
        <xs:attribute name="manager" type="xs:string" />
        <xs:attribute name="version" type="xs:float" />
        <xs:attribute name="status" type="xs:string" />
        <xs:attribute name="authors" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="module" type="Module" />

</xs:schema>

=== gdmatrix/gdmatrix4/modules/elections.xml
<?xml version="1.0" encoding="UTF-8"?>
<module
  xmlns="http://schema.gdmatrix.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schema.gdmatrix.org module.xsd"
  name="elections"
  namespace="http://elections.matrix.org/"
  title="Elections manager"
  manager="ElectionsManager"
  version="1.1"
  status="REVISION"
  authors="Ricard Real">

  <attribute name="jaxws.wsdlLocation" value="/services/elections?wsdl" />
  <attribute name="jaxrs.path" value="/elections" />

  <imports>
    <import prefix="mx"
      namespace="http://base.matrix.org/"
      location="matrix.xsd" />
  </imports>

  <types>

    <entity name="Councillor">
      <identifier name="partyId">
      </identifier>
      <property name="order" type="xs:int">
      </property>
      <property name="name" type="xs:string" minOccurs="0">
      </property>
      <property name="imageURL" type="xs:string" minOccurs="0">
      </property>
    </entity>

    <entity name="PoliticalParty">
      <identifier name="partyId">
      </identifier>
      <property name="abbreviation" type="xs:string" minOccurs="0">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="image" type="xs:string" minOccurs="0">
      </property>
      <property name="color" type="xs:string" minOccurs="0">
      </property>
    </entity>

    <entity name="Board">
      <identifier name="districtId">
      </identifier>
      <property name="sectionId" type="xs:string" minOccurs="0">
      </property>
      <property name="boardId" type="xs:string" minOccurs="0">
      </property>
      <property name="electors" type="xs:int">
      </property>
      <property name="totalVotes" type="xs:int">
      </property>
      <property name="blankVotes" type="xs:int">
      </property>
      <property name="nullVotes" type="xs:int">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
    </entity>

    <entity name="ElectionsResult">
      <identifier name="partyId">
      </identifier>
      <property name="districtId" type="xs:string" minOccurs="0">
      </property>
      <property name="sectionId" type="xs:string" minOccurs="0">
      </property>
      <property name="boardId" type="xs:string" minOccurs="0">
      </property>
      <property name="votes" type="xs:int">
      </property>
    </entity>

    <entity name="Call">
      <identifier name="callId">
      </identifier>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="date" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="councillorsCount" type="xs:int">
      </property>
    </entity>

    <entity name="District">
      <identifier name="districtId">
      </identifier>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
    </entity>
  </types>

  <operations>

    <operation name="listCouncillors">
      <parameter name="date" type="mx:dateTime">
      </parameter>
      <parameter name="callId" type="xs:string">
      </parameter>
      <response name="councillor" type="elections:Councillor" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="listPoliticalParties">
      <parameter name="date" type="mx:dateTime">
      </parameter>
      <parameter name="callId" type="xs:string">
      </parameter>
      <response name="politicalParty" type="elections:PoliticalParty"
        minOccurs="0" maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="listBoards">
      <parameter name="date" type="mx:dateTime">
      </parameter>
      <parameter name="callId" type="xs:string">
      </parameter>
      <response name="board" type="elections:Board" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="listResults">
      <parameter name="date" type="mx:dateTime">
      </parameter>
      <parameter name="callId" type="xs:string">
      </parameter>
      <response name="electionResult" type="elections:ElectionsResult"
        minOccurs="0" maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="listCalls">
      <response name="call" type="elections:Call" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="listDistricts">
      <parameter name="date" type="mx:dateTime">
      </parameter>
      <response name="district" type="elections:District" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>
  </operations>
</module>

=== gdmatrix/gdmatrix4/modules/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<module
  xmlns="http://schema.gdmatrix.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schema.gdmatrix.org module.xsd"
  name="report"
  namespace="http://report.matrix.org/"
  title="Report generator"
  manager="ReportManager"
  version="1.0"
  status="REVISION"
  authors="Ricard Real">

  <attribute name="jaxws.wsdlLocation" value="/services/report?wsdl" />
  <attribute name="jaxrs.path" value="/report" />

  <imports>
    <import prefix="mx"
      namespace="http://base.matrix.org/"
      location="matrix.xsd" />
    <import module="doc"/>
  </imports>

  <types>

    <entity name="Report" extends="doc:Document">
      <identifier name="reportId">
      </identifier>
      <property name="technology" type="xs:string" minOccurs="0">
      </property>
      <property name="defaultConnectionName" type="xs:string" minOccurs="0">
      </property>
      <property name="parameterDefinition" type="report:ParameterDefinition"
        minOccurs="0" maxOccurs="unbounded" nillable="true">
      </property>
    </entity>

    <struct name="ParameterDefinition">
      <property name="name" type="xs:string" minOccurs="0">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="type" type="report:ParameterType" minOccurs="0">
      </property>
      <property name="forPrompting" type="xs:boolean">
      </property>
      <property name="defaultValue" type="xs:string" minOccurs="0">
      </property>
    </struct>

    <struct name="Parameter">
      <property name="name" type="xs:string" minOccurs="0">
      </property>
      <property name="value" type="xs:string" minOccurs="0">
      </property>
    </struct>

    <struct name="ExportOptions">
      <property name="format" type="xs:string" minOccurs="0">
      </property>
      <property name="fromPage" type="xs:int" minOccurs="0">
      </property>
      <property name="toPage" type="xs:int" minOccurs="0">
      </property>
      <property name="ignorePagination" type="xs:boolean">
      </property>
      <property name="ignorePageMargins" type="xs:boolean">
      </property>
      <property name="characterEncoding" type="xs:string" minOccurs="0">
      </property>
      <property name="parameter" type="report:Parameter" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </property>
    </struct>

    <struct name="ReportFilter">
      <property name="reportId" type="xs:string" minOccurs="0">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="firstResult" type="xs:int">
      </property>
      <property name="maxResults" type="xs:int">
      </property>
    </struct>

    <enumeration name="ParameterType">
      <value name="INTEGER"/>
      <value name="DOUBLE"/>
      <value name="FLOAT"/>
      <value name="STRING"/>
      <value name="DATE"/>
      <value name="BOOLEAN"/>
    </enumeration>
  </types>

  <operations>

    <operation name="loadReport">
      <parameter name="reportId" type="xs:string">
      </parameter>
      <parameter name="includeSourceData" type="xs:boolean">
      </parameter>
      <response name="report" type="report:Report">
      </response>
    </operation>

    <operation name="executeReport">
      <parameter name="reportId" type="xs:string">
      </parameter>
      <parameter name="connectionName" type="xs:string">
      </parameter>
      <parameter name="parameter" type="report:Parameter" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </parameter>
      <parameter name="exportOptions" type="report:ExportOptions">
      </parameter>
      <response name="return" type="xs:base64Binary" expectedContentTypes="*/*">
      </response>
    </operation>

    <operation name="storeReport">
      <parameter name="report" type="report:Report">
      </parameter>
      <response name="storedReport" type="report:Report">
      </response>
    </operation>

    <operation name="removeReport">
      <parameter name="reportId" type="xs:string">
      </parameter>
      <response name="removed" type="xs:boolean">
      </response>
    </operation>

    <operation name="findReports">
      <parameter name="filter" type="report:ReportFilter">
      </parameter>
      <response name="report" type="report:Report" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>
  </operations>
</module>

=== gdmatrix/gdmatrix4/modules/classif.xml
<?xml version="1.0" encoding="UTF-8"?>
<module
  xmlns="http://schema.gdmatrix.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schema.gdmatrix.org module.xsd"
  name="classif"
  namespace="http://classif.matrix.org/"
  title="Classification manager"
  manager="ClassificationManager"
  version="1.0"
  status="FINAL"
  authors="Ricard Real">

  <attribute name="jaxws.wsdlLocation" value="/services/classif?wsdl" />
  <attribute name="jaxrs.path" value="/classif" />

  <imports>
    <import prefix="mx"
      namespace="http://base.matrix.org/"
      location="matrix.xsd" />
    <import module="dic"/>
    <import module="security"/>
  </imports>

  <types>
    <entity name="Class">
      <identifier name="classId">
      </identifier>
      <property name="creationDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="creationUserId" type="xs:string" minOccurs="0" references="security:User">
      </property>
      <property name="startDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="endDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="classTypeId" type="xs:string" minOccurs="0" references="dic:Type">
      </property>
      <property name="title" type="xs:string" minOccurs="0">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="location" type="xs:string" minOccurs="0">
      </property>
      <property name="offlineDownload" type="xs:boolean">
      </property>
      <property name="superClassId" type="xs:string" minOccurs="0" references="classif:Class">
      </property>
      <property name="accessControlUserId" type="xs:string" minOccurs="0">
      </property>
      <property name="changeDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="changeUserId" type="xs:string" minOccurs="0" references="security:User">
      </property>
      <property name="property" type="dic:Property" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </property>
      <property name="changeReason" type="xs:string" minOccurs="0">
      </property>
    </entity>

    <struct name="ClassFilter">
      <property name="classId" type="xs:string" minOccurs="0" references="classif:Class">
      </property>
      <property name="title" type="xs:string" minOccurs="0">
      </property>
      <property name="superClassId" type="xs:string" minOccurs="0" references="classif:Class">
      </property>
      <property name="description" type="xs:string" minOccurs="0">
      </property>
      <property name="startDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="endDateTime" type="mx:dateTime" minOccurs="0">
      </property>
      <property name="firstResult" type="xs:int">
      </property>
      <property name="maxResults" type="xs:int">
      </property>
    </struct>
  </types>

  <operations>
    <operation name="loadClass">
      <parameter name="classId" type="xs:string">
      </parameter>
      <parameter name="dateTime" type="mx:dateTime" nillable="true">
      </parameter>
      <response name="class" type="classif:Class">
      </response>
    </operation>

    <operation name="storeClass">
      <parameter name="class" type="classif:Class">
      </parameter>
      <response name="storedClass" type="classif:Class">
      </response>
    </operation>

    <operation name="removeClass">
      <parameter name="classId" type="xs:string">
      </parameter>
      <response name="removed" type="xs:boolean">
      </response>
    </operation>

    <operation name="findClasses">
      <parameter name="filter" type="classif:ClassFilter">
      </parameter>
      <response name="class" type="classif:Class" minOccurs="0" maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

    <operation name="countClasses">
      <parameter name="filter" type="classif:ClassFilter">
      </parameter>
      <response name="classCount" type="xs:int">
      </response>
    </operation>

    <operation name="listModifiedClasses">
      <attribute name="jaxrs.method" value="GET" />
      <parameter name="dateTime1" type="xs:string">
      </parameter>
      <parameter name="dateTime2" type="xs:string">
      </parameter>
      <response name="classId" type="xs:string" minOccurs="0"
        maxOccurs="unbounded" nillable="true">
      </response>
    </operation>

  </operations>
</module>
